# Generated by Django 3.2.6 on 2021-11-04 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Final price')),
                ('in_order', models.BooleanField(default=False)),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Shipping price')),
                ('for_anonymous_users', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wheels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=500)),
                ('detailed_description', models.TextField(blank=True, max_length=1500)),
                ('availability', models.PositiveIntegerField(default=0)),
                ('thumbnail_image', models.ImageField(upload_to='img/')),
                ('big_image', models.ImageField(upload_to='img/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Brake_Rotor_Mount_Type', models.CharField(max_length=10)),
                ('Rim_Internal_Width', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Tubeless_Ready', models.BooleanField()),
                ('Material', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Carbon'), (2, 'Aluminium'), (3, 'Titan'), (4, 'Steel')], default=1, max_length=7)),
                ('Wheel_size', multiselectfield.db.fields.MultiSelectField(choices=[(1, '24'), (2, '26'), (3, '27.5'), (4, '29')], default=1, max_length=7)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Wheels',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Name')),
                ('second_name', models.CharField(max_length=255, verbose_name='Second Name')),
                ('phone_number', models.CharField(max_length=22, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address, ZIP Code')),
                ('status', models.CharField(choices=[('new', 'New order'), ('in_progress', 'Order in progress'), ('is_ready', 'Order is ready'), ('is_completed', 'Order completed')], default='new', max_length=255, verbose_name='Order status')),
                ('buying_type', models.CharField(choices=[('self', 'Pickup'), ('in_progress', 'Delivery')], default='self', max_length=255, verbose_name='Order type')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment for order')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Order creation date')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of receipt of the order')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.cart', verbose_name='Cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='web.customer', verbose_name='Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='GlassesAndMasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=500)),
                ('detailed_description', models.TextField(blank=True, max_length=1500)),
                ('availability', models.PositiveIntegerField(default=0)),
                ('thumbnail_image', models.ImageField(upload_to='img/')),
                ('big_image', models.ImageField(upload_to='img/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('color', models.CharField(max_length=35)),
                ('Change_lenses', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Glasses and Masks',
            },
        ),
        migrations.CreateModel(
            name='Forks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=500)),
                ('detailed_description', models.TextField(blank=True, max_length=1500)),
                ('availability', models.PositiveIntegerField(default=0)),
                ('thumbnail_image', models.ImageField(upload_to='img/')),
                ('big_image', models.ImageField(upload_to='img/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Travel', models.CharField(max_length=10)),
                ('Steerer_Diameter', models.CharField(max_length=35)),
                ('Wheel_size', multiselectfield.db.fields.MultiSelectField(choices=[(1, '24'), (2, '26'), (3, '27.5'), (4, '29')], default=1, max_length=7)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Forks',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_customer', to='web.Order', verbose_name="Customer's orders"),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='Cranksets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=500)),
                ('detailed_description', models.TextField(blank=True, max_length=1500)),
                ('availability', models.PositiveIntegerField(default=0)),
                ('thumbnail_image', models.ImageField(upload_to='img/')),
                ('big_image', models.ImageField(upload_to='img/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Chainline', models.CharField(max_length=50)),
                ('Material', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Carbon'), (2, 'Aluminium'), (3, 'Titan'), (4, 'Steel')], default=1, max_length=7)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Cranksets',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Product')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Final price')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='web.cart', verbose_name='Cart')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.customer', verbose_name='Customer')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.customer', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='web.CartProduct'),
        ),
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=500)),
                ('detailed_description', models.TextField(blank=True, max_length=1500)),
                ('availability', models.PositiveIntegerField(default=0)),
                ('thumbnail_image', models.ImageField(upload_to='img/')),
                ('big_image', models.ImageField(upload_to='img/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Brakes', models.CharField(max_length=100)),
                ('Fork', models.CharField(max_length=100)),
                ('Transmission', models.CharField(max_length=100)),
                ('Frame_material', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Carbon'), (2, 'Aluminium'), (3, 'Titan'), (4, 'Steel')], default=1, max_length=7)),
                ('Wheel_size', multiselectfield.db.fields.MultiSelectField(choices=[(1, '24'), (2, '26'), (3, '27.5'), (4, '29')], default=1, max_length=7)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Bikes',
            },
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=500)),
                ('detailed_description', models.TextField(blank=True, max_length=1500)),
                ('availability', models.PositiveIntegerField(default=0)),
                ('thumbnail_image', models.ImageField(upload_to='img/')),
                ('big_image', models.ImageField(upload_to='img/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('type', models.CharField(max_length=25)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Accessories',
            },
        ),
    ]
