# Generated by Django 3.2.6 on 2021-09-04 12:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('detailed_description', models.TextField(max_length=1500)),
                ('availability', models.PositiveIntegerField(default=0)),
                ('thumbnail_image', models.ImageField(upload_to='img/')),
                ('big_image', models.ImageField(upload_to='img/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('choice_where', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Add to new arrivals'), (2, 'Only to shop page')], default=2, max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
