# Generated by Django 3.2.6 on 2021-09-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
