# Generated by Django 3.2.6 on 2021-09-05 15:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_products_detailed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Shirts'), (2, 'Shoes'), (3, 'Trousers'), (4, 'Hats'), (5, 'Glasses'), (6, 'Jewelry')], default=1, max_length=11),
            preserve_default=False,
        ),
    ]
