# Generated by Django 3.2.6 on 2021-09-08 15:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210908_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=35)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=35)),
                ('Brakes', models.CharField(max_length=100)),
                ('Fork', models.CharField(max_length=100)),
                ('Transmission', models.CharField(max_length=100)),
                ('Frame_material', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Carbon'), (2, 'Aluminium'), (3, 'Titan'), (4, 'Steel')], default=1, max_length=7)),
                ('Wheel_size', multiselectfield.db.fields.MultiSelectField(choices=[(1, '24'), (2, '26'), (3, '27.5'), (4, '29')], default=1, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Cranksets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=35)),
                ('Chainline', models.CharField(max_length=50)),
                ('Material', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Carbon'), (2, 'Aluminium'), (3, 'Titan'), (4, 'Steel')], default=1, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Forks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=35)),
                ('Travel', models.CharField(max_length=10)),
                ('Steerer_Diameter', models.CharField(max_length=35)),
                ('Wheel_size', multiselectfield.db.fields.MultiSelectField(choices=[(1, '24'), (2, '26'), (3, '27.5'), (4, '29')], default=1, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='GlassesAndMasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=35)),
                ('color', models.CharField(max_length=35)),
                ('Change_lenses', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Wheels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=35)),
                ('Brake_Rotor_Mount_Type', models.CharField(max_length=10)),
                ('Rim_Internal_Width', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Tubeless_Ready', models.BooleanField()),
                ('Material', models.CharField(max_length=50)),
                ('Wheel_size', multiselectfield.db.fields.MultiSelectField(choices=[(1, '24'), (2, '26'), (3, '27.5'), (4, '29')], default=1, max_length=7)),
            ],
        ),
    ]
