# Generated by Django 3.2.6 on 2021-11-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_cartproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='second_name',
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default=2, max_length=255, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
