# Generated by Django 3.2.6 on 2021-09-08 15:10

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_accessories_bikes_cranksets_forks_glassesandmasks_wheels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessories',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='bikes',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='cranksets',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='forks',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='glassesandmasks',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='wheels',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='bikes',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='cranksets',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='forks',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='glassesandmasks',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='wheels',
            name='Title',
        ),
        migrations.AddField(
            model_name='accessories',
            name='availability',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accessories',
            name='big_image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessories',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessories',
            name='choice_where',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Add to new arrivals'), (2, 'Only to shop page')], default=2, max_length=3),
        ),
        migrations.AddField(
            model_name='accessories',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='accessories',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='accessories',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='accessories',
            name='thumbnail_image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessories',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessories',
            name='type',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikes',
            name='availability',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bikes',
            name='big_image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikes',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikes',
            name='choice_where',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Add to new arrivals'), (2, 'Only to shop page')], default=2, max_length=3),
        ),
        migrations.AddField(
            model_name='bikes',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikes',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='bikes',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bikes',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='bikes',
            name='thumbnail_image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikes',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cranksets',
            name='availability',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cranksets',
            name='big_image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cranksets',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cranksets',
            name='choice_where',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Add to new arrivals'), (2, 'Only to shop page')], default=2, max_length=3),
        ),
        migrations.AddField(
            model_name='cranksets',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cranksets',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='cranksets',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cranksets',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='cranksets',
            name='thumbnail_image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cranksets',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forks',
            name='availability',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forks',
            name='big_image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forks',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forks',
            name='choice_where',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Add to new arrivals'), (2, 'Only to shop page')], default=2, max_length=3),
        ),
        migrations.AddField(
            model_name='forks',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forks',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='forks',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='forks',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='forks',
            name='thumbnail_image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forks',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glassesandmasks',
            name='availability',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glassesandmasks',
            name='big_image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glassesandmasks',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glassesandmasks',
            name='choice_where',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Add to new arrivals'), (2, 'Only to shop page')], default=2, max_length=3),
        ),
        migrations.AddField(
            model_name='glassesandmasks',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glassesandmasks',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='glassesandmasks',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='glassesandmasks',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='glassesandmasks',
            name='thumbnail_image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glassesandmasks',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wheels',
            name='availability',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wheels',
            name='big_image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wheels',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wheels',
            name='choice_where',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Add to new arrivals'), (2, 'Only to shop page')], default=2, max_length=3),
        ),
        migrations.AddField(
            model_name='wheels',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wheels',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='wheels',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wheels',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='wheels',
            name='thumbnail_image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wheels',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
