# Generated by Django 3.2.6 on 2021-11-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_productfeatures_productfeaturesvalidators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeaturesvalidators',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productfeaturesvalidators',
            name='feature',
        ),
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
        migrations.DeleteModel(
            name='ProductFeaturesValidators',
        ),
    ]
