# Generated by Django 3.2.6 on 2021-09-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210908_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessories',
            options={'verbose_name_plural': 'Accessories'},
        ),
        migrations.AlterModelOptions(
            name='bikes',
            options={'verbose_name_plural': 'Bikes'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='cranksets',
            options={'verbose_name_plural': 'Cranksets'},
        ),
        migrations.AlterModelOptions(
            name='forks',
            options={'verbose_name_plural': 'Forks'},
        ),
        migrations.AlterModelOptions(
            name='glassesandmasks',
            options={'verbose_name_plural': 'Glasses and Masks'},
        ),
        migrations.AlterModelOptions(
            name='wheels',
            options={'verbose_name_plural': 'Wheels'},
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='choice_where',
        ),
        migrations.RemoveField(
            model_name='bikes',
            name='choice_where',
        ),
        migrations.RemoveField(
            model_name='cranksets',
            name='choice_where',
        ),
        migrations.RemoveField(
            model_name='forks',
            name='choice_where',
        ),
        migrations.RemoveField(
            model_name='glassesandmasks',
            name='choice_where',
        ),
        migrations.RemoveField(
            model_name='wheels',
            name='choice_where',
        ),
    ]
