# Generated by Django 3.2.6 on 2021-09-14 17:01

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210911_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wheels',
            name='Material',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Carbon'), (2, 'Aluminium'), (3, 'Titan'), (4, 'Steel')], default=1, max_length=7),
        ),
    ]
