# Generated by Django 3.2.6 on 2021-10-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20211011_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Shipping price'),
        ),
    ]
